### ISSUE TITLE
Mojave V2.0.0.

### ISSUE THREAD

**Issue by Tina-Chris** [inkstitch/inkstitch#1205]
I got a comment on the youtube Channel regarding problems with the mojave install.

dragonlord0666
sadly, I downloaded version 2 for mojave and installed it, now inkscape (1.0+) will not run and just crashes upon opening.

even tried a restore from time machine backup and a reboot - still can't get inkscape to work now so what ever inkstitch did, it did a good job of killing my working version of inkscape and inkstitch - not happy!!!

I answered the following, linking @dragonlord0666 back to this thread. 
Do you get a crash message? Maybe you need to do the same as for BigSur or Catalina? https://inkstitch.org/docs/install-macos/#addtitional-steps-for-catalina--big-sur 
I opened a github issue for your problem: https://github.com/inkstitch/inkstitch/issues/1205 
You're welcome to post the error messages or other helpful details for bugfixing there. I'm sorry it caused you trouble. 
- Tina

**Comment by kaalleen** [comment]
Sorry to hear that. I heard about this issue once.

The problem has been solved by the following steps:

* remove the whole inkscape folder (~/Library/Application\ Support/org.inkscape.Inkscape/config/inkscape)
* startup Inkscape to recreate that folder
* close Inkscape (some users reported that it is important on macOS systems to not have Inkscape running while installing Ink/Stitch)
* Copy the Ink/Stitch files into the extensions folder
* Start Inkscape

I hope it helps... In rare cases it might even be necessary to reinstall Inkscape. I am not sure why.

The additional steps from the website are not necessary for Mojave. macOS introduced the singing procedure for Catalina and it only effects Catalina and newer systems (Big Sur).

**Comment by kaalleen** [comment]
I am just wondering about the user name... I just read an other issue from dragonlord66666 (#1200). Maybe it's not Inkscape which is crashing but only some/all(?) Ink/Stitch extensions (such as params)?

**Comment by dragonlord66666** [comment]
yes that is me
inkstitch will not run. params opens then quickly closes. it did kill my perferences.xml file which stopped inkscape from opening and I had to find and deleted that and inkscape now works. had to reset all my settings like themes and views etc.)

inkstitch 2 still won't work. I now get the error that inkstitch quit unexpectedly when I try to open params
![Screenshot 2021-05-13 at 6 29 37 am](https://user-images.githubusercontent.com/81831005/118082210-a9409800-b3b4-11eb-8471-f7ba67234a91.png)

**Comment by dragonlord66666** [comment]
inkscape was NOT running when I installed inkstitch - have tried both unzipping inkstitch to desktop and copy/paste the folder in the extensions folder and unzipping inkstitch directly in the extensions folder - neither worked.

**Comment by dragonlord66666** [comment]
still not working.
I have removed the shapely folder. still not working
I have set inkstitch to be trusted to open both via System Preferences>Security&Privacy and via terminal as in the Catalina extra steps - still not working

I closed inkscape each time BEFORE I changed anything and reopened it

I still get params opens then closes and I get the error of inkstitch quit unexpectedly - tried with different shapes, even one drawn from the bezier tool all have just a fill, no stroke on them (circles etc. I converted to paths via both path>object to path or path>union)

**Comment by dragonlord66666** [comment]
it's something to do with FILLS causing the problem
I tried re-downloading the mojave zip of inkstitch 2.0 English, unzipped it and copied all the files in the inkstitch-v2.0.0-osx-mojave-en_US folder into the inkstitch-v2.0.0-osx-mojave-en_US in the extensions folder.
tried it and it worked - great I thought. then noticed in preview it was only the outline so I cancelled it and set the fill, removed stroke and went extension>inkstitch>params and it opens then closes again with the quit error. so it has something to do with the fill stopping it loading / running as it works if I only have a stroke set (stroke is a solid line NOT a dash one)
![Screenshot 2021-05-13 at 11 22 29 pm](https://user-images.githubusercontent.com/81831005/118194975-38e05800-b442-11eb-824b-2039c742d29f.png)

**Comment by kaalleen** [comment]
Wow, I have no idea what is going on. I had several people testing the new version on Mojave and nobody reported any errors like that. I really have no idea how to help at this point. But I am wondering about the last image you posted. It looks like embroidery params and the preview window are combined as tabs in a window called Preview. That is very odd. I've never seen it like that (and it is not supposed to do that). Did it open like this natively?

**Comment by dragonlord66666** [comment]
yes, it always has opened like this even in version 1 both opened as tabs.

**Comment by dragonlord66666** [comment]
gone back to version 1 as at least that works. but as you can see, params and preview have always been a tabbed thing
![Screenshot 2021-05-14 at 7 06 26 pm](https://user-images.githubusercontent.com/81831005/118311503-e6f20d80-b4e7-11eb-8b00-74e2dc1a5b62.png)

does not matter is I put inkstitch in the user preferences or the one inside inkscape (yes I did try this with inkstitch 2. made no difference)
guess I just can have inkstitch 2

**Comment by kaalleen** [comment]
Uhm, that's not very satisfying. I just don't know what to do about it, sorry.

**Comment by kaalleen** [comment]
@dragonlord66666 I wondering if this only happens with the params or if it is an issue with fills in general.

Would you mind to try an other output extension on the fill object... Such as e.g. stitch plan (which should render the fill object to appear on the left side of the canvas), also try to run troubleshoot and see if that does anything strange.

Maybe you want to try a smaller fill area than the one in your pictures too. Just to save you some time.

**Comment by kaalleen** [comment]
@dragonlord66666 When you run parameter on a fill object and it crashes. Can you run Finder > Applications > Utilities > Council

Search for inkstitch and see if it has any information about the crash. If so, post it here.

**Comment by kaalleen** [comment]
No answer for a quite long time. I hope this issue has been solved or will be solved with the next release. Please reopen, if those problems are remaining.

@dragonlord66666
