### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Maschkenator** [inkstitch/inkstitch#3018]
Trying to save the SVG to PES and got this error. The initial file came from .ai...even converted all lines/paths with Inkscape vectors because I thought that's the problem (since I cannot convert them to Satin)...

Ink/Stitch Version: 3.0.1 (osx)

Traceback (most recent call last):
  File "inkstitch.py", line 84, in <module>
  File "inkex/base.py", line 231, in run
  File "lib/extensions/output.py", line 57, in effect
  File "lib/stitch_plan/stitch_plan.py", line 46, in stitch_groups_to_stitch_plan
  File "lib/threads/color.py", line 76, in __ne__
  File "lib/threads/color.py", line 70, in __eq__
  File "lib/threads/color.py", line 36, in __init__
TypeError: 'NoneType' object is not iterable

![bracket v3](https://github.com/inkstitch/inkstitch/assets/32331862/7efec74f-44d3-46cc-87c1-ef232ed38ad9)

**Comment by tyrosinase** [comment]
This is fixed in the upcoming version. It crops up when certain non-Inkscape files are used and Ink/Stitch doesn't recognize the way the colors are recorded.

For now, re-apply colors from the Inkscape palette and it'll be happy.

Don't forget to group all the yellow dots and all the black dots or you'll have a lot of unnecessary color changes:

![image](https://github.com/inkstitch/inkstitch/assets/9473609/caa54b17-5868-4315-bed2-5107e92b8ce5)

**Comment by Maschkenator** [comment]
I clicked on every item and selected an Inkscape color from the pallet; i re-did every fill-and-stroke item... but I am getting the exact same error...
Except for :
File "inkstitch.py", line 84, in _<module>_

I am still unable to save as a .pes ... saved as a new svg, re-opened the project on a PC but same error...not sure what else to do. I tried other color pallets, too. No luck. I know I'm a noob, so I'm sure I'm missing something...?!

Can you point me to the specific issue you are seeing / I am missing in this file?

![bracket v4](https://github.com/inkstitch/inkstitch/assets/32331862/68a7448d-6fec-48b8-9fea-3d0fdecc9f9f)

**Comment by tyrosinase** [comment]
The black outlined pieces still had a fill (just a transparent one). You also had a couple of different blacks, so I made them the same (Sulky 1000, so if you have a different palette make sure you change both the fill and stroke). And zigzag is generally fine for curved pieces but it doesn't follow corners properly so I converted it to satin. And your page size was 4" so I changed it to 100mm; Ink/Stitch doesn't actually care what the Inkscape page size is but most "4x4" machines are really 100mm (though I've encountered at least one that was 98x102mm). You can put the pages in Inkscape's presets with the instructions on this page: https://silverseams.com/embroidery-patterns/basting-boxes/index.html

See if your version of Ink/Stitch will handle the SVG with the transparent fills removed; if not it's the full ZIP.

[342868377-68a7448d-6fec-48b8-9fea-3d0fdecc9f9f.zip](https://github.com/user-attachments/files/15981678/342868377-68a7448d-6fec-48b8-9fea-3d0fdecc9f9f.zip)

I'm currently running the `simulator-line-width` release, which has the fix in it. I think most of the current ones do, so if you want to you can go to the main project page and install a pre-release and that should clear it up (though you shouldn't have invisible fills in any release, it confuses things and hmm, maybe Troubleshooting should point them out).

![image](https://github.com/inkstitch/inkstitch/assets/9473609/9bf0f51d-e8fa-40bf-8410-5a592c629f91)
