### ISSUE TITLE
AttributeError: 'MultiPolygon' object has no attribute 'exterior'

### ISSUE THREAD

**Issue by AVK636** [inkstitch/inkstitch#3595]
I have a path in an svg, where whenever I try to set a negative "Expand" and a "Pull compensation percentage", I get the following error:
````
Ink/Stitch experienced an unexpected error. This means it is a bug in Ink/Stitch.

If you'd like to help please
- copy the entire error message below
- save your SVG file and
- create a new issue at https://github.com/inkstitch/inkstitch/issues/new

Include the error description and also (if possible) the svg file.

Windows 10 version: 10.0.19045

Ink/Stitch Version: v3.1.0 (windows) 2024-07-27 09:04

Traceback (most recent call last):
  File "lib\elements\element.py", line 641, in handle_unexpected_exceptions
  File "lib\elements\element.py", line 605, in embroider
  File "lib\elements\fill_stitch.py", line 961, in to_stitch_groups
  File "lib\elements\fill_stitch.py", line 1044, in do_auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 92, in auto_fill
  File "lib\debug\debug.py", line 166, in decorated
  File "lib\stitches\auto_fill.py", line 143, in adjust_shape_for_pull_compensation
AttributeError: 'MultiPolygon' object has no attribute 'exterior'
````
The svg is attached. The error occurs for the path "head". The weird thing is, that I already successfully stitched that exact shape, with -1mm expand and 2.5% pull compensation. I edited the svg afterwards but not this particular path. What causes this error?

![Image](https://github.com/user-attachments/assets/dee076a6-c3b7-4daf-8066-921218f88a35)

**Comment by tyrosinase** [comment]
There's a bug in the current version, fixed by #3143, that sometimes causes a corruption in the final shape. (And yeah, it's weird that sometimes transient errors are triggered not by changes in the Inkscape shape, but by the state of the shapes right before/after it.)

Sometimes you can work around it by changing the offending node(s) (like #3164, where it was fairly obvious), or you can run a development release that includes 3143 in it. I'm not sure there's official documentation on doing it but https://silverseams.com/2024/04/installing-pre-releases.html goes through it.

(I'm going to close the issue but that doesn't close the conversation, if you have more questions)

**Comment by AVK636** [comment]
Thanks for the quick answer! The pre-release version indeed fixes the error, however rendering the preview of the offended shape now takes 5-15 minutes, instead of the usual few seconds. So while I'm glad it works, it's still not optimal. I had a closer look into the nodes looking for some signs, that could cause this problem, however, for me, everything looks fine. Is there a possibility to troubleshoot this problem further?
